name: Release and Publish to NPM

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm release
